language: scala

scala:
   - 2.10.4
   - 2.11.11

jdk: oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
  - BUILD_LABEL=1.0.${TRAVIS_BUILD_NUMBER}
  - secure: M2tmhBeJQ89bUbXZSMJQ65Fbjrhu9I/NvxP9jS+92AZm7NTpqp1CmAxjK3bVT8oBBUdlHRD8A/823bWUOHe0fnRHuOd8YG+O+srBXMO4XntpeLp63FXW1nwSyCQJXkw4WRn7xCxJZgl1X6XGHgwjI/J0MS9xAbH9BdcmfTlrvck/B03fhgMQR7cpPaUdhxzsJ33yiqjx2w2rl1BbQ4VsfqZrMiUbLC2w4KT6AmeZEhp+GcrqsMN34ZsxD7gKibdHhr4IiEgsUNVs3+t2Zw9D432mOfGplB8TI30Yfnq0nvBdngXZI83dpCEYK/iPO36voZaFpJrj3FR8tU2zC2etNn+HxogiJe18+XEo2+/5o554fuua7NczXURt7H6MACl8w/jsLOT/FmtMq4NRdSV2+YprkX83x+2wJw/dq3wWRLvHl+ADlys+kHwXgaTEgvVBOzqKWj3lqQgjjhOLPehUqhi5+55hdPq88o2E+VuxXUIUbzoB482+BJdaNlkPr9we3OPsa3yY/OFqIlIBMZ5iJLq5Nt3dRHmxkxtzTqUkwKZik/CjsvIZE5/sj9Xcgjd9kTYBmNYy+LRezwOPwn+m4fn2Y6/yprv4LCFJT4MeJuHCT5PpPCwPbAw9G2wWT8H2O4I+QuyhwsWGw8cAe3MKKxzPky493GfbHmdtn0dhxRo=
  - secure: ZvHMbibCOn9h6iUHj4+O4NL1nMoRKPN3rS/4+Tc3cjbBClz+iH40clEuIg8EJ+ybieRa4UrqF5SKstrM+RXBZ40EVYnNWbvBePxFqRh26ALEAeKbTvGOYNpsMeMtDdceiRVPvHlXLD2/MDMi49KQp57pNopVe/4z7PKYWxwvnPzssu5SNTxwzvrw1Zvt6T6cJoI2heDm9z7XEHogdvjGgqnJYZKu4aWqPxJMqlngQvhnBtPkimCSxT0Fd50Sg8rk6nf209ZQEpN+8VLuVxzFfvx/BudfCosfVsNwtUwdtF3D+5AkQKJWd/ktkgZKRXUgwacJ1o73ljn9Xi84PbEXxnRMlKBjELY/YFfWLttwBx7SVqy6aDFdUd3S7WeOrMe2GHL3t9LUqc3EQxBCkB9sOfTDIzmPAaCMgZiLJUkDBPo1wtPgHwZAM7ej7xCiWjFZeGTylz6HypSiJycEgWevgzMrSTahEjOG4/sV6S3MPjHjSf5x5GE+7y8AjdqvcU/+Fu89Yimn842OlY6PENLxNh1n0+1LLNBfNMnwCHOyU1ctwljtHlQ6N9zjFSAPSE3OIiykhyOIZt10zC7ZLi+UorkfU5gEixxqr8Qtqw8b/WGurOSVUr+6+zGExepJHxMGSXsIv1T/9+1mN1mHR4pV3YM1hlKxJDyqHe6SPRdiffg=
  - secure: K4kindqdxpPvjuAax3dvgop+UfN9az/7opfen+BuIV0wzJfw4as2LKOb6XBopPMBetM45xInOjz2iBTxOgFUhmSuT262/F021urMGhpmJOFVpFp7hwddAPp9909cHXA4Wy++cJpUsn7C4b5lSfytASxQgX3ypf7cXtf50zPOZfar5QQQxPz7f7sPdFcoRsw18ZPBkMALxSUlkYdOqRW0/7+zy9rG5eV7G1gTfG+Orvg/9UzzNx77qSB+e0TBf8gZVohifXshEAZ/hk9VIauRG2EXWIQ5UY1fiWJPTJ+4qqNmRA7cSJdKRmtAe6fUFmGIqBbHgZT3P+EBJTACGosJ96kmMC9YmJ/Ijc1zytx8/1ytcb7HUzNRoTyVn9Ebb16SfsoS+vkjJvfolr6antgLNKxprPvyn7Pqh2wTVYbCu9Wm1cVQ/1nlT7MtFUkYBwFVdESDvn/JC3Y2pakkeEGGl94ESErl7U5I8cWemB8DkcvcndtzOMmLhiS7c4xvIQQXmMM64bVudZetPRnelbG7gBjUEzfvkP4QxsZwzCZxDodv3YfHm/zeCMMKp6tE+sMoUQF86svHDHoOJa8s43OWot2lz7FRPGedr6NjTmHbbDGFQ6OPbKzgz/SFbhaCyK/afWs9jBYXdXRm6JlRKR7cW/PbTYDjcnozlwIRgmeF08g=
  - secure: VQCaatgK2E/GEbx8tvH12LnRHfvuGNdc+PbfciDSA9mPvtRz0SCchyXW0DEA7HZb9CiD4TVoY6V+cbf2DXM7ZSfe6dPBRKQBOsNAfCAkkDRWUJ3JxGWytnb8irkdk8ulqsfQ75G/lqVqnVEPQfu1yCtYWmCfNe55SzqIX0orYgvrMlhzxk7vufZnLTM1D0BD3RF9ELQ4WAFaib7y/3jlttkzhUQEdDT8WZNBhs8pyteE7iOdhlvq+8JIppgygyP43DNuOgVd/fg77IFlBFh/ukvXd8X5b/7J7NXwtvOZhPqWy+B0vejbrLB7Ndtw6cyZcRyYLl23I/OZ5CuJ4PyiAYqDMV0qdVFihO7J7vIocGlul7b+VU498RAmzOtt/eJhn9FpnqN9Y0fMIMYz73lrmZ3k8RggKHVER2icy4Ig9G+3TNufs3aEjrY3RhZRpqVUSm7mtLCNjfiZQmYnkuTApj1mfS5dVYDuDBK0DxTw6waR/eV+596n2ryt9W3ZCGR99BIpcmcZPg4qPrJOsKHvZy+4LZDkXoWPsYT8vR56N2dWoOCAiItVs38+yZnxVK1Gbp+OG7xMnXRgeklfvmAHe87wat3n7AoBbvV6KZZbAT8xmFxVRLF5Q/EOqqAEUMqZD8EPtJZVEqzkZFySBg3O6EQM/H9la+wlzCZZIZr5z1g=


before_deploy:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg -d

deploy:
  - provider: script
    script: "./publish.sh"
    skip_cleanup: true
    on:
      tags: true
      jdk: oraclejdk8
      scala: "2.11.11"

notifications:
  slack:
    rooms:
      secure: HQdcZwqDY9+vGW7N9YZ2tFeU50SgqrWEQefI/injWVcndkAL7U/TFOoFvyOdxPZA1sya3aKUyAfVVv7BzMdPUfas41LgYj+iSWAaidiwqrJMp3lkvvALoXId9IDrdWcbhqJ4F51dfO8ck6Jf0S9cXtXC8/dSunWJORdr9ycgkxs=
    on_success: change
    on_failure: always